@extends('layouts.app')
@section('title', 'Create Order')
@section('content')
<form method="POST" action="{{ route('orders.store') }}" class="row g-4">@csrf
<div class="col-lg-8"><div class="card p-4"><div class="d-flex justify-content-between mb-3"><h2 class="h6">Laundry Items</h2><button type="button" id="addItem" class="btn btn-outline-success btn-sm">Add Item</button></div><div id="items"><div class="row g-2 item-row mb-2"><div class="col-md-5"><input name="items[0][item_name]" class="form-control" placeholder="Item name" required></div><div class="col-md-3"><input type="number" name="items[0][quantity]" class="form-control qty" value="1" min="1" required></div><div class="col-md-3"><input type="number" step="0.1" name="items[0][weight_kg]" class="form-control weight" value="1" min="0.1" required></div><div class="col-md-1"><button type="button" class="btn btn-outline-danger w-100 remove">x</button></div></div></div></div></div>
<div class="col-lg-4"><div class="card p-4"><h2 class="h6 mb-3">Summary</h2><div class="d-flex justify-content-between"><span>Total weight</span><strong><span id="totalWeight">1.00</span> kg</strong></div><div class="d-flex justify-content-between mt-2"><span>Estimated price</span><strong>PHP <span id="totalPrice">65.00</span></strong></div><button class="btn btn-success w-100 mt-4">Submit Order</button></div></div>
</form>
@push('scripts')<script>let index=1;function recalc(){let t=0;document.querySelectorAll('.item-row').forEach(r=>t+=(parseFloat(r.querySelector('.qty').value||0)*parseFloat(r.querySelector('.weight').value||0)));totalWeight.textContent=t.toFixed(2);totalPrice.textContent=(t*65).toFixed(2)}addItem.onclick=()=>{items.insertAdjacentHTML('beforeend',`<div class="row g-2 item-row mb-2"><div class="col-md-5"><input name="items[${index}][item_name]" class="form-control" placeholder="Item name" required></div><div class="col-md-3"><input type="number" name="items[${index}][quantity]" class="form-control qty" value="1" min="1" required></div><div class="col-md-3"><input type="number" step="0.1" name="items[${index}][weight_kg]" class="form-control weight" value="1" min="0.1" required></div><div class="col-md-1"><button type="button" class="btn btn-outline-danger w-100 remove">x</button></div></div>`);index++;recalc()};document.addEventListener('input',e=>{if(e.target.matches('.qty,.weight'))recalc()});document.addEventListener('click',e=>{if(e.target.closest('.remove')&&document.querySelectorAll('.item-row').length>1){e.target.closest('.item-row').remove();recalc()}});</script>@endpush
@endsection
