<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class PokedexController extends Controller
{
    private $pokemonData = [
        // === GEN I SHOWCASE (1-10) ===
        1 => ['id' => 1, 'pokedex_number' => '#0001', 'name' => 'Bulbasaur', 'type' => 'Grass/Poison', 'generation' => 'Gen I', 'ability' => 'Overgrow', 'habitat' => 'Grasslands', 'evolution' => 'Ivysaur', 'image' => 'bulbasaur.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 101, 'final_evolution_id' => 102],
        2 => ['id' => 2, 'pokedex_number' => '#0004', 'name' => 'Charmander', 'type' => 'Fire', 'generation' => 'Gen I', 'ability' => 'Blaze', 'habitat' => 'Mountains', 'evolution' => 'Charmeleon', 'image' => 'charmander.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 103, 'final_evolution_id' => 104],
        3 => ['id' => 3, 'pokedex_number' => '#0007', 'name' => 'Squirtle', 'type' => 'Water', 'generation' => 'Gen I', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Wartortle', 'image' => 'squirtle.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 105, 'final_evolution_id' => 106],
        4 => ['id' => 4, 'pokedex_number' => '#0010', 'name' => 'Caterpie', 'type' => 'Bug', 'generation' => 'Gen I', 'ability' => 'Shield Dust', 'habitat' => 'Forests', 'evolution' => 'Metapod', 'image' => 'caterpie.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 107, 'final_evolution_id' => 108],
        5 => ['id' => 5, 'pokedex_number' => '#0013', 'name' => 'Weedle', 'type' => 'Bug/Poison', 'generation' => 'Gen I', 'ability' => 'Shield Dust', 'habitat' => 'Forests', 'evolution' => 'Kakuna', 'image' => 'weedle.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 109, 'final_evolution_id' => 110],
        6 => ['id' => 6, 'pokedex_number' => '#0016', 'name' => 'Pidgey', 'type' => 'Normal/Flying', 'generation' => 'Gen I', 'ability' => 'Keen Eye', 'habitat' => 'Forests', 'evolution' => 'Pidgeotto', 'image' => 'pidgey.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 111, 'final_evolution_id' => 112],
        7 => ['id' => 7, 'pokedex_number' => '#0019', 'name' => 'Rattata', 'type' => 'Normal', 'generation' => 'Gen I', 'ability' => 'Run Away', 'habitat' => 'Grasslands', 'evolution' => 'Raticate', 'image' => 'rattata.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 113, 'final_evolution_id' => null],
        8 => ['id' => 8, 'pokedex_number' => '#0021', 'name' => 'Spearow', 'type' => 'Normal/Flying', 'generation' => 'Gen I', 'ability' => 'Keen Eye', 'habitat' => 'Grasslands', 'evolution' => 'Fearow', 'image' => 'spearow.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 114, 'final_evolution_id' => null],
        9 => ['id' => 9, 'pokedex_number' => '#0023', 'name' => 'Ekans', 'type' => 'Poison', 'generation' => 'Gen I', 'ability' => 'Intimidate', 'habitat' => 'Grasslands', 'evolution' => 'Arbok', 'image' => 'ekans.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 115, 'final_evolution_id' => null],
        10 => ['id' => 10, 'pokedex_number' => '#0025', 'name' => 'Pikachu', 'type' => 'Electric', 'generation' => 'Gen I', 'ability' => 'Static', 'habitat' => 'Forests', 'evolution' => 'Raichu', 'image' => 'pikachu.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 116, 'final_evolution_id' => null],

        // === GEN I EVOLUTIONS (101+) ===
        101 => ['id' => 101, 'pokedex_number' => '#0002', 'name' => 'Ivysaur', 'type' => 'Grass/Poison', 'generation' => 'Gen I', 'ability' => 'Overgrow', 'habitat' => 'Grasslands', 'evolution' => 'Venusaur', 'image' => 'ivysaur.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 102, 'final_evolution_id' => null],
        102 => ['id' => 102, 'pokedex_number' => '#0003', 'name' => 'Venusaur', 'type' => 'Grass/Poison', 'generation' => 'Gen I', 'ability' => 'Overgrow', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'venusaur.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        103 => ['id' => 103, 'pokedex_number' => '#0005', 'name' => 'Charmeleon', 'type' => 'Fire', 'generation' => 'Gen I', 'ability' => 'Blaze', 'habitat' => 'Mountains', 'evolution' => 'Charizard', 'image' => 'charmeleon.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 104, 'final_evolution_id' => null],
        104 => ['id' => 104, 'pokedex_number' => '#0006', 'name' => 'Charizard', 'type' => 'Fire/Flying', 'generation' => 'Gen I', 'ability' => 'Blaze', 'habitat' => 'Mountains', 'evolution' => 'Final Form', 'image' => 'charizard.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        105 => ['id' => 105, 'pokedex_number' => '#0008', 'name' => 'Wartortle', 'type' => 'Water', 'generation' => 'Gen I', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Blastoise', 'image' => 'wartortle.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 106, 'final_evolution_id' => null],
        106 => ['id' => 106, 'pokedex_number' => '#0009', 'name' => 'Blastoise', 'type' => 'Water', 'generation' => 'Gen I', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Final Form', 'image' => 'blastoise.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        107 => ['id' => 107, 'pokedex_number' => '#0011', 'name' => 'Metapod', 'type' => 'Bug', 'generation' => 'Gen I', 'ability' => 'Shed Skin', 'habitat' => 'Forests', 'evolution' => 'Butterfree', 'image' => 'metapod.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 108, 'final_evolution_id' => null],
        108 => ['id' => 108, 'pokedex_number' => '#0012', 'name' => 'Butterfree', 'type' => 'Bug/Flying', 'generation' => 'Gen I', 'ability' => 'Compound Eyes', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'butterfree.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        109 => ['id' => 109, 'pokedex_number' => '#0014', 'name' => 'Kakuna', 'type' => 'Bug/Poison', 'generation' => 'Gen I', 'ability' => 'Shed Skin', 'habitat' => 'Forests', 'evolution' => 'Beedrill', 'image' => 'kakuna.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 110, 'final_evolution_id' => null],
        110 => ['id' => 110, 'pokedex_number' => '#0015', 'name' => 'Beedrill', 'type' => 'Bug/Poison', 'generation' => 'Gen I', 'ability' => 'Swarm', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'beedrill.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        111 => ['id' => 111, 'pokedex_number' => '#0017', 'name' => 'Pidgeotto', 'type' => 'Normal/Flying', 'generation' => 'Gen I', 'ability' => 'Keen Eye', 'habitat' => 'Forests', 'evolution' => 'Pidgeot', 'image' => 'pidgeotto.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 112, 'final_evolution_id' => null],
        112 => ['id' => 112, 'pokedex_number' => '#0018', 'name' => 'Pidgeot', 'type' => 'Normal/Flying', 'generation' => 'Gen I', 'ability' => 'Keen Eye', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'pidgeot.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        113 => ['id' => 113, 'pokedex_number' => '#0020', 'name' => 'Raticate', 'type' => 'Normal', 'generation' => 'Gen I', 'ability' => 'Run Away', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'raticate.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        114 => ['id' => 114, 'pokedex_number' => '#0022', 'name' => 'Fearow', 'type' => 'Normal/Flying', 'generation' => 'Gen I', 'ability' => 'Keen Eye', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'fearow.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        115 => ['id' => 115, 'pokedex_number' => '#0024', 'name' => 'Arbok', 'type' => 'Poison', 'generation' => 'Gen I', 'ability' => 'Intimidate', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'arbok.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        116 => ['id' => 116, 'pokedex_number' => '#0026', 'name' => 'Raichu', 'type' => 'Electric', 'generation' => 'Gen I', 'ability' => 'Static', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'raichu.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],

        // === GEN II SHOWCASE (11-20) ===
        11 => ['id' => 11, 'pokedex_number' => '#0152', 'name' => 'Chikorita', 'type' => 'Grass', 'generation' => 'Gen II', 'ability' => 'Overgrow', 'habitat' => 'Grasslands', 'evolution' => 'Bayleef', 'image' => 'chikorita.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 201, 'final_evolution_id' => 202],
        12 => ['id' => 12, 'pokedex_number' => '#0155', 'name' => 'Cyndaquil', 'type' => 'Fire', 'generation' => 'Gen II', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Quilava', 'image' => 'cyndaquil.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 203, 'final_evolution_id' => 204],
        13 => ['id' => 13, 'pokedex_number' => '#0158', 'name' => 'Totodile', 'type' => 'Water', 'generation' => 'Gen II', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Croconaw', 'image' => 'totodile.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 205, 'final_evolution_id' => 206],
        14 => ['id' => 14, 'pokedex_number' => '#0161', 'name' => 'Sentret', 'type' => 'Normal', 'generation' => 'Gen II', 'ability' => 'Run Away', 'habitat' => 'Grasslands', 'evolution' => 'Furret', 'image' => 'sentret.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 207, 'final_evolution_id' => null],
        15 => ['id' => 15, 'pokedex_number' => '#0163', 'name' => 'Hoothoot', 'type' => 'Normal/Flying', 'generation' => 'Gen II', 'ability' => 'Insomnia', 'habitat' => 'Forests', 'evolution' => 'Noctowl', 'image' => 'hoothoot.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 208, 'final_evolution_id' => null],
        16 => ['id' => 16, 'pokedex_number' => '#0165', 'name' => 'Ledyba', 'type' => 'Bug/Flying', 'generation' => 'Gen II', 'ability' => 'Swarm', 'habitat' => 'Forests', 'evolution' => 'Ledian', 'image' => 'ledyba.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 209, 'final_evolution_id' => null],
        17 => ['id' => 17, 'pokedex_number' => '#0167', 'name' => 'Spinarak', 'type' => 'Bug/Poison', 'generation' => 'Gen II', 'ability' => 'Swarm', 'habitat' => 'Forests', 'evolution' => 'Ariados', 'image' => 'spinarak.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 210, 'final_evolution_id' => null],
        18 => ['id' => 18, 'pokedex_number' => '#0170', 'name' => 'Chinchou', 'type' => 'Water/Electric', 'generation' => 'Gen II', 'ability' => 'Volt Absorb', 'habitat' => 'Sea', 'evolution' => 'Lanturn', 'image' => 'chinchou.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 211, 'final_evolution_id' => null],
        19 => ['id' => 19, 'pokedex_number' => '#0175', 'name' => 'Togepi', 'type' => 'Fairy', 'generation' => 'Gen II', 'ability' => 'Hustle', 'habitat' => 'Forests', 'evolution' => 'Togetic', 'image' => 'togepi.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 212, 'final_evolution_id' => 213],
        20 => ['id' => 20, 'pokedex_number' => '#0179', 'name' => 'Mareep', 'type' => 'Electric', 'generation' => 'Gen II', 'ability' => 'Static', 'habitat' => 'Grasslands', 'evolution' => 'Flaaffy', 'image' => 'mareep.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 214, 'final_evolution_id' => 215],

        // === GEN II EVOLUTIONS (201+) ===
        201 => ['id' => 201, 'pokedex_number' => '#0153', 'name' => 'Bayleef', 'type' => 'Grass', 'generation' => 'Gen II', 'ability' => 'Overgrow', 'habitat' => 'Grasslands', 'evolution' => 'Meganium', 'image' => 'bayleef.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 202, 'final_evolution_id' => null],
        202 => ['id' => 202, 'pokedex_number' => '#0154', 'name' => 'Meganium', 'type' => 'Grass', 'generation' => 'Gen II', 'ability' => 'Overgrow', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'meganium.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        203 => ['id' => 203, 'pokedex_number' => '#0156', 'name' => 'Quilava', 'type' => 'Fire', 'generation' => 'Gen II', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Typhlosion', 'image' => 'quilava.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 204, 'final_evolution_id' => null],
        204 => ['id' => 204, 'pokedex_number' => '#0157', 'name' => 'Typhlosion', 'type' => 'Fire', 'generation' => 'Gen II', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'typhlosion.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        205 => ['id' => 205, 'pokedex_number' => '#0159', 'name' => 'Croconaw', 'type' => 'Water', 'generation' => 'Gen II', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Feraligatr', 'image' => 'croconaw.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 206, 'final_evolution_id' => null],
        206 => ['id' => 206, 'pokedex_number' => '#0160', 'name' => 'Feraligatr', 'type' => 'Water', 'generation' => 'Gen II', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Final Form', 'image' => 'feraligatr.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        207 => ['id' => 207, 'pokedex_number' => '#0162', 'name' => 'Furret', 'type' => 'Normal', 'generation' => 'Gen II', 'ability' => 'Run Away', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'furret.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        208 => ['id' => 208, 'pokedex_number' => '#0164', 'name' => 'Noctowl', 'type' => 'Normal/Flying', 'generation' => 'Gen II', 'ability' => 'Insomnia', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'noctowl.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        209 => ['id' => 209, 'pokedex_number' => '#0166', 'name' => 'Ledian', 'type' => 'Bug/Flying', 'generation' => 'Gen II', 'ability' => 'Swarm', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'ledian.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        210 => ['id' => 210, 'pokedex_number' => '#0168', 'name' => 'Ariados', 'type' => 'Bug/Poison', 'generation' => 'Gen II', 'ability' => 'Swarm', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'ariados.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        211 => ['id' => 211, 'pokedex_number' => '#0171', 'name' => 'Lanturn', 'type' => 'Water/Electric', 'generation' => 'Gen II', 'ability' => 'Volt Absorb', 'habitat' => 'Sea', 'evolution' => 'Final Form', 'image' => 'lanturn.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        212 => ['id' => 212, 'pokedex_number' => '#0176', 'name' => 'Togetic', 'type' => 'Fairy/Flying', 'generation' => 'Gen II', 'ability' => 'Serene Grace', 'habitat' => 'Forests', 'evolution' => 'Togekiss', 'image' => 'togetic.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 213, 'final_evolution_id' => null],
        213 => ['id' => 213, 'pokedex_number' => '#0468', 'name' => 'Togekiss', 'type' => 'Fairy/Flying', 'generation' => 'Gen IV', 'ability' => 'Serene Grace', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'togekiss.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        214 => ['id' => 214, 'pokedex_number' => '#0180', 'name' => 'Flaaffy', 'type' => 'Electric', 'generation' => 'Gen II', 'ability' => 'Static', 'habitat' => 'Grasslands', 'evolution' => 'Ampharos', 'image' => 'flaaffy.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 215, 'final_evolution_id' => null],
        215 => ['id' => 215, 'pokedex_number' => '#0181', 'name' => 'Ampharos', 'type' => 'Electric', 'generation' => 'Gen II', 'ability' => 'Static', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'ampharos.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],

        // === GEN III SHOWCASE (21-30) ===
        21 => ['id' => 21, 'pokedex_number' => '#0252', 'name' => 'Treecko', 'type' => 'Grass', 'generation' => 'Gen III', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Grovyle', 'image' => 'treecko.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 301, 'final_evolution_id' => 302],
        22 => ['id' => 22, 'pokedex_number' => '#0255', 'name' => 'Torchic', 'type' => 'Fire', 'generation' => 'Gen III', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Combusken', 'image' => 'torchic.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 303, 'final_evolution_id' => 304],
        23 => ['id' => 23, 'pokedex_number' => '#0258', 'name' => 'Mudkip', 'type' => 'Water', 'generation' => 'Gen III', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Marshtomp', 'image' => 'mudkip.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 305, 'final_evolution_id' => 306],
        24 => ['id' => 24, 'pokedex_number' => '#0261', 'name' => 'Poochyena', 'type' => 'Dark', 'generation' => 'Gen III', 'ability' => 'Run Away', 'habitat' => 'Grasslands', 'evolution' => 'Mightyena', 'image' => 'poochyena.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 307, 'final_evolution_id' => null],
        25 => ['id' => 25, 'pokedex_number' => '#0263', 'name' => 'Zigzagoon', 'type' => 'Normal', 'generation' => 'Gen III', 'ability' => 'Pickup', 'habitat' => 'Grasslands', 'evolution' => 'Linoone', 'image' => 'zigzagoon.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 308, 'final_evolution_id' => null],
        26 => ['id' => 26, 'pokedex_number' => '#0265', 'name' => 'Wurmple', 'type' => 'Bug', 'generation' => 'Gen III', 'ability' => 'Shield Dust', 'habitat' => 'Forests', 'evolution' => 'Silcoon/Cascoon', 'image' => 'wurmple.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 309, 'final_evolution_id' => 310],
        27 => ['id' => 27, 'pokedex_number' => '#0270', 'name' => 'Lotad', 'type' => 'Water/Grass', 'generation' => 'Gen III', 'ability' => 'Swift Swim', 'habitat' => 'Water\'s Edge', 'evolution' => 'Lombre', 'image' => 'lotad.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 311, 'final_evolution_id' => 312],
        28 => ['id' => 28, 'pokedex_number' => '#0273', 'name' => 'Seedot', 'type' => 'Grass', 'generation' => 'Gen III', 'ability' => 'Chlorophyll', 'habitat' => 'Forests', 'evolution' => 'Nuzleaf', 'image' => 'seedot.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 313, 'final_evolution_id' => 314],
        29 => ['id' => 29, 'pokedex_number' => '#0276', 'name' => 'Taillow', 'type' => 'Normal/Flying', 'generation' => 'Gen III', 'ability' => 'Guts', 'habitat' => 'Grasslands', 'evolution' => 'Swellow', 'image' => 'taillow.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 315, 'final_evolution_id' => null],
        30 => ['id' => 30, 'pokedex_number' => '#0278', 'name' => 'Wingull', 'type' => 'Water/Flying', 'generation' => 'Gen III', 'ability' => 'Keen Eye', 'habitat' => 'Water\'s Edge', 'evolution' => 'Pelipper', 'image' => 'wingull.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 316, 'final_evolution_id' => null],

        // === GEN III EVOLUTIONS (301+) ===
        301 => ['id' => 301, 'pokedex_number' => '#0253', 'name' => 'Grovyle', 'type' => 'Grass', 'generation' => 'Gen III', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Sceptile', 'image' => 'grovyle.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 302, 'final_evolution_id' => null],
        302 => ['id' => 302, 'pokedex_number' => '#0254', 'name' => 'Sceptile', 'type' => 'Grass', 'generation' => 'Gen III', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'sceptile.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        303 => ['id' => 303, 'pokedex_number' => '#0256', 'name' => 'Combusken', 'type' => 'Fire/Fighting', 'generation' => 'Gen III', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Blaziken', 'image' => 'combusken.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 304, 'final_evolution_id' => null],
        304 => ['id' => 304, 'pokedex_number' => '#0257', 'name' => 'Blaziken', 'type' => 'Fire/Fighting', 'generation' => 'Gen III', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'blaziken.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        305 => ['id' => 305, 'pokedex_number' => '#0259', 'name' => 'Marshtomp', 'type' => 'Water/Ground', 'generation' => 'Gen III', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Swampert', 'image' => 'marshtomp.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 306, 'final_evolution_id' => null],
        306 => ['id' => 306, 'pokedex_number' => '#0260', 'name' => 'Swampert', 'type' => 'Water/Ground', 'generation' => 'Gen III', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Final Form', 'image' => 'swampert.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        307 => ['id' => 307, 'pokedex_number' => '#0262', 'name' => 'Mightyena', 'type' => 'Dark', 'generation' => 'Gen III', 'ability' => 'Intimidate', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'mightyena.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        308 => ['id' => 308, 'pokedex_number' => '#0264', 'name' => 'Linoone', 'type' => 'Normal', 'generation' => 'Gen III', 'ability' => 'Gluttony', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'linoone.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        309 => ['id' => 309, 'pokedex_number' => '#0266', 'name' => 'Silcoon', 'type' => 'Bug', 'generation' => 'Gen III', 'ability' => 'Shed Skin', 'habitat' => 'Forests', 'evolution' => 'Beautifly', 'image' => 'silcoon.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 310, 'final_evolution_id' => null],
        310 => ['id' => 310, 'pokedex_number' => '#0267', 'name' => 'Beautifly', 'type' => 'Bug/Flying', 'generation' => 'Gen III', 'ability' => 'Swarm', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'beautifly.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        311 => ['id' => 311, 'pokedex_number' => '#0271', 'name' => 'Lombre', 'type' => 'Water/Grass', 'generation' => 'Gen III', 'ability' => 'Swift Swim', 'habitat' => 'Water\'s Edge', 'evolution' => 'Ludicolo', 'image' => 'lombre.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 312, 'final_evolution_id' => null],
        312 => ['id' => 312, 'pokedex_number' => '#0272', 'name' => 'Ludicolo', 'type' => 'Water/Grass', 'generation' => 'Gen III', 'ability' => 'Swift Swim', 'habitat' => 'Water\'s Edge', 'evolution' => 'Final Form', 'image' => 'ludicolo.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        313 => ['id' => 313, 'pokedex_number' => '#0274', 'name' => 'Nuzleaf', 'type' => 'Grass/Dark', 'generation' => 'Gen III', 'ability' => 'Chlorophyll', 'habitat' => 'Forests', 'evolution' => 'Shiftry', 'image' => 'nuzleaf.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 314, 'final_evolution_id' => null],
        314 => ['id' => 314, 'pokedex_number' => '#0275', 'name' => 'Shiftry', 'type' => 'Grass/Dark', 'generation' => 'Gen III', 'ability' => 'Chlorophyll', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'shiftry.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        315 => ['id' => 315, 'pokedex_number' => '#0277', 'name' => 'Swellow', 'type' => 'Normal/Flying', 'generation' => 'Gen III', 'ability' => 'Guts', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'swellow.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        316 => ['id' => 316, 'pokedex_number' => '#0279', 'name' => 'Pelipper', 'type' => 'Water/Flying', 'generation' => 'Gen III', 'ability' => 'Keen Eye', 'habitat' => 'Water\'s Edge', 'evolution' => 'Final Form', 'image' => 'pelipper.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],

        // ... Continues for Gen IV - IX (same unique pattern)
        31 => ['id' => 31, 'pokedex_number' => '#0387', 'name' => 'Turtwig', 'type' => 'Grass', 'generation' => 'Gen IV', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Grotle', 'image' => 'turtwig.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 401, 'final_evolution_id' => 402],
        32 => ['id' => 32, 'pokedex_number' => '#0390', 'name' => 'Chimchar', 'type' => 'Fire', 'generation' => 'Gen IV', 'ability' => 'Blaze', 'habitat' => 'Mountains', 'evolution' => 'Monferno', 'image' => 'chimchar.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 403, 'final_evolution_id' => 404],
        33 => ['id' => 33, 'pokedex_number' => '#0393', 'name' => 'Piplup', 'type' => 'Water', 'generation' => 'Gen IV', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Prinplup', 'image' => 'piplup.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 405, 'final_evolution_id' => 406],
        34 => ['id' => 34, 'pokedex_number' => '#0396', 'name' => 'Starly', 'type' => 'Normal/Flying', 'generation' => 'Gen IV', 'ability' => 'Keen Eye', 'habitat' => 'Forests', 'evolution' => 'Staravia', 'image' => 'starly.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 407, 'final_evolution_id' => 408],
        35 => ['id' => 35, 'pokedex_number' => '#0399', 'name' => 'Bidoof', 'type' => 'Normal', 'generation' => 'Gen IV', 'ability' => 'Simple', 'habitat' => 'Water\'s Edge', 'evolution' => 'Bibarel', 'image' => 'bidoof.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 409, 'final_evolution_id' => null],
        36 => ['id' => 36, 'pokedex_number' => '#0401', 'name' => 'Kricketot', 'type' => 'Bug', 'generation' => 'Gen IV', 'ability' => 'Shed Skin', 'habitat' => 'Forests', 'evolution' => 'Kricketune', 'image' => 'kricketot.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 410, 'final_evolution_id' => null],
        37 => ['id' => 37, 'pokedex_number' => '#0403', 'name' => 'Shinx', 'type' => 'Electric', 'generation' => 'Gen IV', 'ability' => 'Rivalry', 'habitat' => 'Grasslands', 'evolution' => 'Luxio', 'image' => 'shinx.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 411, 'final_evolution_id' => 412],
        38 => ['id' => 38, 'pokedex_number' => '#0406', 'name' => 'Budew', 'type' => 'Grass/Poison', 'generation' => 'Gen IV', 'ability' => 'Natural Cure', 'habitat' => 'Forests', 'evolution' => 'Roselia', 'image' => 'budew.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 413, 'final_evolution_id' => 414],
        39 => ['id' => 39, 'pokedex_number' => '#0412', 'name' => 'Burmy', 'type' => 'Bug', 'generation' => 'Gen IV', 'ability' => 'Shed Skin', 'habitat' => 'Forests', 'evolution' => 'Wormadam', 'image' => 'burmy.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 415, 'final_evolution_id' => null],
        40 => ['id' => 40, 'pokedex_number' => '#0418', 'name' => 'Buizel', 'type' => 'Water', 'generation' => 'Gen IV', 'ability' => 'Swift Swim', 'habitat' => 'Water\'s Edge', 'evolution' => 'Floatzel', 'image' => 'buizel.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 416, 'final_evolution_id' => null],

        // GEN IV Evolutions (401+)
        401 => ['id' => 401, 'pokedex_number' => '#0388', 'name' => 'Grotle', 'type' => 'Grass', 'generation' => 'Gen IV', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Torterra', 'image' => 'grotle.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 402, 'final_evolution_id' => null],
        402 => ['id' => 402, 'pokedex_number' => '#0389', 'name' => 'Torterra', 'type' => 'Grass/Ground', 'generation' => 'Gen IV', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'torterra.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        403 => ['id' => 403, 'pokedex_number' => '#0391', 'name' => 'Monferno', 'type' => 'Fire/Fighting', 'generation' => 'Gen IV', 'ability' => 'Blaze', 'habitat' => 'Mountains', 'evolution' => 'Infernape', 'image' => 'monferno.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 404, 'final_evolution_id' => null],
        404 => ['id' => 404, 'pokedex_number' => '#0392', 'name' => 'Infernape', 'type' => 'Fire/Fighting', 'generation' => 'Gen IV', 'ability' => 'Blaze', 'habitat' => 'Mountains', 'evolution' => 'Final Form', 'image' => 'infernape.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        405 => ['id' => 405, 'pokedex_number' => '#0394', 'name' => 'Prinplup', 'type' => 'Water', 'generation' => 'Gen IV', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Empoleon', 'image' => 'prinplup.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 406, 'final_evolution_id' => null],
        406 => ['id' => 406, 'pokedex_number' => '#0395', 'name' => 'Empoleon', 'type' => 'Water/Steel', 'generation' => 'Gen IV', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Final Form', 'image' => 'empoleon.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        407 => ['id' => 407, 'pokedex_number' => '#0397', 'name' => 'Staravia', 'type' => 'Normal/Flying', 'generation' => 'Gen IV', 'ability' => 'Intimidate', 'habitat' => 'Forests', 'evolution' => 'Staraptor', 'image' => 'staravia.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 408, 'final_evolution_id' => null],
        408 => ['id' => 408, 'pokedex_number' => '#0398', 'name' => 'Staraptor', 'type' => 'Normal/Flying', 'generation' => 'Gen IV', 'ability' => 'Intimidate', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'staraptor.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        409 => ['id' => 409, 'pokedex_number' => '#0400', 'name' => 'Bibarel', 'type' => 'Normal/Water', 'generation' => 'Gen IV', 'ability' => 'Unaware', 'habitat' => 'Water\'s Edge', 'evolution' => 'Final Form', 'image' => 'bibarel.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        410 => ['id' => 410, 'pokedex_number' => '#0402', 'name' => 'Kricketune', 'type' => 'Bug', 'generation' => 'Gen IV', 'ability' => 'Swarm', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'kricketune.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        411 => ['id' => 411, 'pokedex_number' => '#0404', 'name' => 'Luxio', 'type' => 'Electric', 'generation' => 'Gen IV', 'ability' => 'Rivalry', 'habitat' => 'Grasslands', 'evolution' => 'Luxray', 'image' => 'luxio.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 412, 'final_evolution_id' => null],
        412 => ['id' => 412, 'pokedex_number' => '#0405', 'name' => 'Luxray', 'type' => 'Electric', 'generation' => 'Gen IV', 'ability' => 'Rivalry', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'luxray.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        413 => ['id' => 413, 'pokedex_number' => '#0315', 'name' => 'Roselia', 'type' => 'Grass/Poison', 'generation' => 'Gen III', 'ability' => 'Natural Cure', 'habitat' => 'Forests', 'evolution' => 'Roserade', 'image' => 'roselia.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 414, 'final_evolution_id' => null],
        414 => ['id' => 414, 'pokedex_number' => '#0407', 'name' => 'Roserade', 'type' => 'Grass/Poison', 'generation' => 'Gen IV', 'ability' => 'Natural Cure', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'roserade.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        415 => ['id' => 415, 'pokedex_number' => '#0413', 'name' => 'Wormadam', 'type' => 'Bug/Grass', 'generation' => 'Gen IV', 'ability' => 'Anticipation', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'wormadam.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        416 => ['id' => 416, 'pokedex_number' => '#0419', 'name' => 'Floatzel', 'type' => 'Water', 'generation' => 'Gen IV', 'ability' => 'Swift Swim', 'habitat' => 'Water\'s Edge', 'evolution' => 'Final Form', 'image' => 'floatzel.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],

        // GEN V SHOWCASE (41-50)
        41 => ['id' => 41, 'pokedex_number' => '#0495', 'name' => 'Snivy', 'type' => 'Grass', 'generation' => 'Gen V', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Servine', 'image' => 'snivy.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 501, 'final_evolution_id' => 502],
        42 => ['id' => 42, 'pokedex_number' => '#0498', 'name' => 'Tepig', 'type' => 'Fire', 'generation' => 'Gen V', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Pignite', 'image' => 'tepig.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 503, 'final_evolution_id' => 504],
        43 => ['id' => 43, 'pokedex_number' => '#0501', 'name' => 'Oshawott', 'type' => 'Water', 'generation' => 'Gen V', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Dewott', 'image' => 'oshawott.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 505, 'final_evolution_id' => 506],
        44 => ['id' => 44, 'pokedex_number' => '#0504', 'name' => 'Patrat', 'type' => 'Normal', 'generation' => 'Gen V', 'ability' => 'Run Away', 'habitat' => 'Grasslands', 'evolution' => 'Watchog', 'image' => 'patrat.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 507, 'final_evolution_id' => null],
        45 => ['id' => 45, 'pokedex_number' => '#0506', 'name' => 'Lillipup', 'type' => 'Normal', 'generation' => 'Gen V', 'ability' => 'Vital Spirit', 'habitat' => 'Grasslands', 'evolution' => 'Herdier', 'image' => 'lillipup.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 508, 'final_evolution_id' => 509],
        46 => ['id' => 46, 'pokedex_number' => '#0509', 'name' => 'Purrloin', 'type' => 'Dark', 'generation' => 'Gen V', 'ability' => 'Limber', 'habitat' => 'Grasslands', 'evolution' => 'Liepard', 'image' => 'purrloin.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 510, 'final_evolution_id' => null],
        47 => ['id' => 47, 'pokedex_number' => '#0511', 'name' => 'Pansage', 'type' => 'Grass', 'generation' => 'Gen V', 'ability' => 'Gluttony', 'habitat' => 'Forests', 'evolution' => 'Simisage', 'image' => 'pansage.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 5111, 'final_evolution_id' => null],
        48 => ['id' => 48, 'pokedex_number' => '#0513', 'name' => 'Pansear', 'type' => 'Fire', 'generation' => 'Gen V', 'ability' => 'Gluttony', 'habitat' => 'Forests', 'evolution' => 'Simisear', 'image' => 'pansear.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 5112, 'final_evolution_id' => null],
        49 => ['id' => 49, 'pokedex_number' => '#0515', 'name' => 'Panpour', 'type' => 'Water', 'generation' => 'Gen V', 'ability' => 'Gluttony', 'habitat' => 'Forests', 'evolution' => 'Simipour', 'image' => 'panpour.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 5113, 'final_evolution_id' => null],
        50 => ['id' => 50, 'pokedex_number' => '#0517', 'name' => 'Munna', 'type' => 'Psychic', 'generation' => 'Gen V', 'ability' => 'Forewarn', 'habitat' => 'Forests', 'evolution' => 'Musharna', 'image' => 'munna.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 5114, 'final_evolution_id' => null],

        // GEN V Evolutions (501+)
        501 => ['id' => 501, 'pokedex_number' => '#0496', 'name' => 'Servine', 'type' => 'Grass', 'generation' => 'Gen V', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Serperior', 'image' => 'servine.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 502, 'final_evolution_id' => null],
        502 => ['id' => 502, 'pokedex_number' => '#0497', 'name' => 'Serperior', 'type' => 'Grass', 'generation' => 'Gen V', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'serperior.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        503 => ['id' => 503, 'pokedex_number' => '#0499', 'name' => 'Pignite', 'type' => 'Fire/Fighting', 'generation' => 'Gen V', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Emboar', 'image' => 'pignite.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 504, 'final_evolution_id' => null],
        504 => ['id' => 504, 'pokedex_number' => '#0500', 'name' => 'Emboar', 'type' => 'Fire/Fighting', 'generation' => 'Gen V', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'emboar.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        505 => ['id' => 505, 'pokedex_number' => '#0502', 'name' => 'Dewott', 'type' => 'Water', 'generation' => 'Gen V', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Samurott', 'image' => 'dewott.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 506, 'final_evolution_id' => null],
        506 => ['id' => 506, 'pokedex_number' => '#0503', 'name' => 'Samurott', 'type' => 'Water', 'generation' => 'Gen V', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Final Form', 'image' => 'samurott.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        507 => ['id' => 507, 'pokedex_number' => '#0505', 'name' => 'Watchog', 'type' => 'Normal', 'generation' => 'Gen V', 'ability' => 'Keen Eye', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'watchog.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        508 => ['id' => 508, 'pokedex_number' => '#0507', 'name' => 'Herdier', 'type' => 'Normal', 'generation' => 'Gen V', 'ability' => 'Intimidate', 'habitat' => 'Grasslands', 'evolution' => 'Stoutland', 'image' => 'herdier.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 509, 'final_evolution_id' => null],
        509 => ['id' => 509, 'pokedex_number' => '#0508', 'name' => 'Stoutland', 'type' => 'Normal', 'generation' => 'Gen V', 'ability' => 'Intimidate', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'stoutland.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        510 => ['id' => 510, 'pokedex_number' => '#0510', 'name' => 'Liepard', 'type' => 'Dark', 'generation' => 'Gen V', 'ability' => 'Limber', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'liepard.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        5111 => ['id' => 5111, 'pokedex_number' => '#0512', 'name' => 'Simisage', 'type' => 'Grass', 'generation' => 'Gen V', 'ability' => 'Gluttony', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'simisage.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        5112 => ['id' => 5112, 'pokedex_number' => '#0514', 'name' => 'Simisear', 'type' => 'Fire', 'generation' => 'Gen V', 'ability' => 'Gluttony', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'simisear.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        5113 => ['id' => 5113, 'pokedex_number' => '#0516', 'name' => 'Simipour', 'type' => 'Water', 'generation' => 'Gen V', 'ability' => 'Gluttony', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'simipour.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        5114 => ['id' => 5114, 'pokedex_number' => '#0518', 'name' => 'Musharna', 'type' => 'Psychic', 'generation' => 'Gen V', 'ability' => 'Forewarn', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'musharna.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],

        // ... Patterns repeat for Gen VI, VII, VIII, IX (Showcase 10 unique, Evolutions separate)
        // Adding placeholders for VI-IX showcase to ensure 10 per gen
        51 => ['id' => 51, 'pokedex_number' => '#0650', 'name' => 'Chespin', 'type' => 'Grass', 'generation' => 'Gen VI', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Quilladin', 'image' => 'chespin.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 601, 'final_evolution_id' => 602],
        52 => ['id' => 52, 'pokedex_number' => '#0653', 'name' => 'Fennekin', 'type' => 'Fire', 'generation' => 'Gen VI', 'ability' => 'Blaze', 'habitat' => 'Forests', 'evolution' => 'Braixen', 'image' => 'fennekin.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 603, 'final_evolution_id' => 604],
        53 => ['id' => 53, 'pokedex_number' => '#0656', 'name' => 'Froakie', 'type' => 'Water', 'generation' => 'Gen VI', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Frogadier', 'image' => 'froakie.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 605, 'final_evolution_id' => 606],
        54 => ['id' => 54, 'pokedex_number' => '#0659', 'name' => 'Bunnelby', 'type' => 'Normal', 'generation' => 'Gen VI', 'ability' => 'Cheek Pouch', 'habitat' => 'Grasslands', 'evolution' => 'Diggersby', 'image' => 'bunnelby.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 607, 'final_evolution_id' => null],
        55 => ['id' => 55, 'pokedex_number' => '#0661', 'name' => 'Fletchling', 'type' => 'Normal/Flying', 'generation' => 'Gen VI', 'ability' => 'Big Pecks', 'habitat' => 'Forests', 'evolution' => 'Fletchinder', 'image' => 'fletchling.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 608, 'final_evolution_id' => 609],
        56 => ['id' => 56, 'pokedex_number' => '#0664', 'name' => 'Scatterbug', 'type' => 'Bug', 'generation' => 'Gen VI', 'ability' => 'Shield Dust', 'habitat' => 'Forests', 'evolution' => 'Spewpa', 'image' => 'scatterbug.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 610, 'final_evolution_id' => 611],
        57 => ['id' => 57, 'pokedex_number' => '#0667', 'name' => 'Litleo', 'type' => 'Normal/Fire', 'generation' => 'Gen VI', 'ability' => 'Rivalry', 'habitat' => 'Grasslands', 'evolution' => 'Pyroar', 'image' => 'litleo.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 612, 'final_evolution_id' => null],
        58 => ['id' => 58, 'pokedex_number' => '#0669', 'name' => 'Flabébé', 'type' => 'Fairy', 'generation' => 'Gen VI', 'ability' => 'Flower Veil', 'habitat' => 'Forests', 'evolution' => 'Floette', 'image' => 'flabebe.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 613, 'final_evolution_id' => 614],
        59 => ['id' => 59, 'pokedex_number' => '#0672', 'name' => 'Skiddo', 'type' => 'Grass', 'generation' => 'Gen VI', 'ability' => 'Sap Sipper', 'habitat' => 'Grasslands', 'evolution' => 'Gogoat', 'image' => 'skiddo.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 615, 'final_evolution_id' => null],
        60 => ['id' => 60, 'pokedex_number' => '#0674', 'name' => 'Pancham', 'type' => 'Fighting', 'generation' => 'Gen VI', 'ability' => 'Iron Fist', 'habitat' => 'Forests', 'evolution' => 'Pangoro', 'image' => 'pancham.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 616, 'final_evolution_id' => null],

        // VI Evolutions (601+)
        601 => ['id' => 601, 'pokedex_number' => '#0651', 'name' => 'Quilladin', 'type' => 'Grass', 'generation' => 'Gen VI', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Chesnaught', 'image' => 'quilladin.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 602, 'final_evolution_id' => null],
        602 => ['id' => 602, 'pokedex_number' => '#0652', 'name' => 'Chesnaught', 'type' => 'Grass/Fighting', 'generation' => 'Gen VI', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'chesnaught.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        603 => ['id' => 603, 'pokedex_number' => '#0654', 'name' => 'Braixen', 'type' => 'Fire', 'generation' => 'Gen VI', 'ability' => 'Blaze', 'habitat' => 'Forests', 'evolution' => 'Delphox', 'image' => 'braixen.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 604, 'final_evolution_id' => null],
        604 => ['id' => 604, 'pokedex_number' => '#0655', 'name' => 'Delphox', 'type' => 'Fire/Psychic', 'generation' => 'Gen VI', 'ability' => 'Blaze', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'delphox.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        605 => ['id' => 605, 'pokedex_number' => '#0657', 'name' => 'Frogadier', 'type' => 'Water', 'generation' => 'Gen VI', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Greninja', 'image' => 'frogadier.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 606, 'final_evolution_id' => null],
        606 => ['id' => 606, 'pokedex_number' => '#0658', 'name' => 'Greninja', 'type' => 'Water/Dark', 'generation' => 'Gen VI', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Final Form', 'image' => 'greninja.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        607 => ['id' => 607, 'pokedex_number' => '#0660', 'name' => 'Diggersby', 'type' => 'Normal/Ground', 'generation' => 'Gen VI', 'ability' => 'Cheek Pouch', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'diggersby.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        608 => ['id' => 608, 'pokedex_number' => '#0662', 'name' => 'Fletchinder', 'type' => 'Fire/Flying', 'generation' => 'Gen VI', 'ability' => 'Flame Body', 'habitat' => 'Forests', 'evolution' => 'Talonflame', 'image' => 'fletchinder.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 609, 'final_evolution_id' => null],
        609 => ['id' => 609, 'pokedex_number' => '#0663', 'name' => 'Talonflame', 'type' => 'Fire/Flying', 'generation' => 'Gen VI', 'ability' => 'Flame Body', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'talonflame.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        610 => ['id' => 610, 'pokedex_number' => '#0665', 'name' => 'Spewpa', 'type' => 'Bug', 'generation' => 'Gen VI', 'ability' => 'Shed Skin', 'habitat' => 'Forests', 'evolution' => 'Vivillon', 'image' => 'spewpa.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 611, 'final_evolution_id' => null],
        611 => ['id' => 611, 'pokedex_number' => '#0666', 'name' => 'Vivillon', 'type' => 'Bug/Flying', 'generation' => 'Gen VI', 'ability' => 'Shield Dust', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'vivillon.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        612 => ['id' => 612, 'pokedex_number' => '#0668', 'name' => 'Pyroar', 'type' => 'Normal/Fire', 'generation' => 'Gen VI', 'ability' => 'Rivalry', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'pyroar.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        613 => ['id' => 613, 'pokedex_number' => '#0670', 'name' => 'Floette', 'type' => 'Fairy', 'generation' => 'Gen VI', 'ability' => 'Flower Veil', 'habitat' => 'Forests', 'evolution' => 'Florges', 'image' => 'floette.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 614, 'final_evolution_id' => null],
        614 => ['id' => 614, 'pokedex_number' => '#0671', 'name' => 'Florges', 'type' => 'Fairy', 'generation' => 'Gen VI', 'ability' => 'Flower Veil', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'florges.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        615 => ['id' => 615, 'pokedex_number' => '#0673', 'name' => 'Gogoat', 'type' => 'Grass', 'generation' => 'Gen VI', 'ability' => 'Sap Sipper', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'gogoat.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        616 => ['id' => 616, 'pokedex_number' => '#0675', 'name' => 'Pangoro', 'type' => 'Fighting/Dark', 'generation' => 'Gen VI', 'ability' => 'Iron Fist', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'pangoro.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],

        // GEN VII SHOWCASE (61-70)
        61 => ['id' => 61, 'pokedex_number' => '#0722', 'name' => 'Rowlet', 'type' => 'Grass/Flying', 'generation' => 'Gen VII', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Dartrix', 'image' => 'rowlet.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 701, 'final_evolution_id' => 702],
        62 => ['id' => 62, 'pokedex_number' => '#0725', 'name' => 'Litten', 'type' => 'Fire', 'generation' => 'Gen VII', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Torracat', 'image' => 'litten.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 703, 'final_evolution_id' => 704],
        63 => ['id' => 63, 'pokedex_number' => '#0728', 'name' => 'Popplio', 'type' => 'Water', 'generation' => 'Gen VII', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Brionne', 'image' => 'popplio.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 705, 'final_evolution_id' => 706],
        64 => ['id' => 64, 'pokedex_number' => '#0731', 'name' => 'Pikipek', 'type' => 'Normal/Flying', 'generation' => 'Gen VII', 'ability' => 'Keen Eye', 'habitat' => 'Forests', 'evolution' => 'Trumbeak', 'image' => 'pikipek.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 707, 'final_evolution_id' => 708],
        65 => ['id' => 65, 'pokedex_number' => '#0734', 'name' => 'Yungoos', 'type' => 'Normal', 'generation' => 'Gen VII', 'ability' => 'Stakeout', 'habitat' => 'Grasslands', 'evolution' => 'Gumshoos', 'image' => 'yungoos.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 709, 'final_evolution_id' => null],
        66 => ['id' => 66, 'pokedex_number' => '#0736', 'name' => 'Grubbin', 'type' => 'Bug', 'generation' => 'Gen VII', 'ability' => 'Swarm', 'habitat' => 'Forests', 'evolution' => 'Charjabug', 'image' => 'grubbin.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 710, 'final_evolution_id' => 711],
        67 => ['id' => 67, 'pokedex_number' => '#0739', 'name' => 'Crabrawler', 'type' => 'Fighting', 'generation' => 'Gen VII', 'ability' => 'Hyper Cutter', 'habitat' => 'Water\'s Edge', 'evolution' => 'Crabominable', 'image' => 'crabrawler.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 712, 'final_evolution_id' => null],
        68 => ['id' => 68, 'pokedex_number' => '#0749', 'name' => 'Mudbray', 'type' => 'Ground', 'generation' => 'Gen VII', 'ability' => 'Own Tempo', 'habitat' => 'Grasslands', 'evolution' => 'Mudsdale', 'image' => 'mudbray.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 715, 'final_evolution_id' => null],
        69 => ['id' => 69, 'pokedex_number' => '#0742', 'name' => 'Cutiefly', 'type' => 'Bug/Fairy', 'generation' => 'Gen VII', 'ability' => 'Honey Gather', 'habitat' => 'Forests', 'evolution' => 'Ribombee', 'image' => 'cutiefly.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 713, 'final_evolution_id' => null],
        70 => ['id' => 70, 'pokedex_number' => '#0744', 'name' => 'Rockruff', 'type' => 'Rock', 'generation' => 'Gen VII', 'ability' => 'Keen Eye', 'habitat' => 'Mountains', 'evolution' => 'Lycanroc', 'image' => 'rockruff.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 714, 'final_evolution_id' => null],

        // VII Evolutions (701+)
        701 => ['id' => 701, 'pokedex_number' => '#0723', 'name' => 'Dartrix', 'type' => 'Grass/Flying', 'generation' => 'Gen VII', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Decidueye', 'image' => 'dartrix.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 702, 'final_evolution_id' => null],
        702 => ['id' => 702, 'pokedex_number' => '#0724', 'name' => 'Decidueye', 'type' => 'Grass/Ghost', 'generation' => 'Gen VII', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'decidueye.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        703 => ['id' => 703, 'pokedex_number' => '#0726', 'name' => 'Torracat', 'type' => 'Fire', 'generation' => 'Gen VII', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Incineroar', 'image' => 'torracat.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 704, 'final_evolution_id' => null],
        704 => ['id' => 704, 'pokedex_number' => '#0727', 'name' => 'Incineroar', 'type' => 'Fire/Dark', 'generation' => 'Gen VII', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'incineroar.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        705 => ['id' => 705, 'pokedex_number' => '#0729', 'name' => 'Brionne', 'type' => 'Water', 'generation' => 'Gen VII', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Primarina', 'image' => 'brionne.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 706, 'final_evolution_id' => null],
        706 => ['id' => 706, 'pokedex_number' => '#0730', 'name' => 'Primarina', 'type' => 'Water/Fairy', 'generation' => 'Gen VII', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Final Form', 'image' => 'primarina.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        707 => ['id' => 707, 'pokedex_number' => '#0732', 'name' => 'Trumbeak', 'type' => 'Normal/Flying', 'generation' => 'Gen VII', 'ability' => 'Keen Eye', 'habitat' => 'Forests', 'evolution' => 'Toucannon', 'image' => 'trumbeak.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 708, 'final_evolution_id' => null],
        708 => ['id' => 708, 'pokedex_number' => '#0733', 'name' => 'Toucannon', 'type' => 'Normal/Flying', 'generation' => 'Gen VII', 'ability' => 'Keen Eye', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'toucannon.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        709 => ['id' => 709, 'pokedex_number' => '#0735', 'name' => 'Gumshoos', 'type' => 'Normal', 'generation' => 'Gen VII', 'ability' => 'Stakeout', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'gumshoos.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        710 => ['id' => 710, 'pokedex_number' => '#0737', 'name' => 'Charjabug', 'type' => 'Bug/Electric', 'generation' => 'Gen VII', 'ability' => 'Battery', 'habitat' => 'Forests', 'evolution' => 'Vikavolt', 'image' => 'charjabug.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 711, 'final_evolution_id' => null],
        711 => ['id' => 711, 'pokedex_number' => '#0738', 'name' => 'Vikavolt', 'type' => 'Bug/Electric', 'generation' => 'Gen VII', 'ability' => 'Levitate', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'vikavolt.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        712 => ['id' => 712, 'pokedex_number' => '#0740', 'name' => 'Crabominable', 'type' => 'Fighting/Ice', 'generation' => 'Gen VII', 'ability' => 'Hyper Cutter', 'habitat' => 'Mountains', 'evolution' => 'Final Form', 'image' => 'crabominable.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        713 => ['id' => 713, 'pokedex_number' => '#0743', 'name' => 'Ribombee', 'type' => 'Bug/Fairy', 'generation' => 'Gen VII', 'ability' => 'Honey Gather', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'ribombee.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        714 => ['id' => 714, 'pokedex_number' => '#0745', 'name' => 'Lycanroc', 'type' => 'Rock', 'generation' => 'Gen VII', 'ability' => 'Keen Eye', 'habitat' => 'Mountains', 'evolution' => 'Final Form', 'image' => 'lycanroc.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        715 => ['id' => 715, 'pokedex_number' => '#0750', 'name' => 'Mudsdale', 'type' => 'Ground', 'generation' => 'Gen VII', 'ability' => 'Stamina', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'mudsdale.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],

        // GEN VIII SHOWCASE (71-80)
        71 => ['id' => 71, 'pokedex_number' => '#0810', 'name' => 'Grookey', 'type' => 'Grass', 'generation' => 'Gen VIII', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Thwackey', 'image' => 'grookey.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 801, 'final_evolution_id' => 802],
        72 => ['id' => 72, 'pokedex_number' => '#0813', 'name' => 'Scorbunny', 'type' => 'Fire', 'generation' => 'Gen VIII', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Raboot', 'image' => 'scorbunny.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 803, 'final_evolution_id' => 804],
        73 => ['id' => 73, 'pokedex_number' => '#0816', 'name' => 'Sobble', 'type' => 'Water', 'generation' => 'Gen VIII', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Drizzile', 'image' => 'sobble.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 805, 'final_evolution_id' => 806],
        74 => ['id' => 74, 'pokedex_number' => '#0819', 'name' => 'Skwovet', 'type' => 'Normal', 'generation' => 'Gen VIII', 'ability' => 'Cheek Pouch', 'habitat' => 'Forests', 'evolution' => 'Greedent', 'image' => 'skwovet.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 807, 'final_evolution_id' => null],
        75 => ['id' => 75, 'pokedex_number' => '#0821', 'name' => 'Rookidee', 'type' => 'Flying', 'generation' => 'Gen VIII', 'ability' => 'Keen Eye', 'habitat' => 'Grasslands', 'evolution' => 'Corvisquire', 'image' => 'rookidee.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 808, 'final_evolution_id' => 809],
        76 => ['id' => 76, 'pokedex_number' => '#0824', 'name' => 'Blipbug', 'type' => 'Bug', 'generation' => 'Gen VIII', 'ability' => 'Swarm', 'habitat' => 'Forests', 'evolution' => 'Dottler', 'image' => 'blipbug.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 810, 'final_evolution_id' => 811],
        77 => ['id' => 77, 'pokedex_number' => '#0827', 'name' => 'Nickit', 'type' => 'Dark', 'generation' => 'Gen VIII', 'ability' => 'Run Away', 'habitat' => 'Grasslands', 'evolution' => 'Thievul', 'image' => 'nickit.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 812, 'final_evolution_id' => null],
        78 => ['id' => 78, 'pokedex_number' => '#0829', 'name' => 'Gossifleur', 'type' => 'Grass', 'generation' => 'Gen VIII', 'ability' => 'Cotton Down', 'habitat' => 'Grasslands', 'evolution' => 'Eldegoss', 'image' => 'gossifleur.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 813, 'final_evolution_id' => null],
        79 => ['id' => 79, 'pokedex_number' => '#0831', 'name' => 'Wooloo', 'type' => 'Normal', 'generation' => 'Gen VIII', 'ability' => 'Fluffy', 'habitat' => 'Grasslands', 'evolution' => 'Dubwool', 'image' => 'wooloo.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 814, 'final_evolution_id' => null],
        80 => ['id' => 80, 'pokedex_number' => '#0833', 'name' => 'Chewtle', 'type' => 'Water', 'generation' => 'Gen VIII', 'ability' => 'Strong Jaw', 'habitat' => 'Water\'s Edge', 'evolution' => 'Drednaw', 'image' => 'chewtle.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 815, 'final_evolution_id' => null],

        // VIII Evolutions (801+)
        801 => ['id' => 801, 'pokedex_number' => '#0811', 'name' => 'Thwackey', 'type' => 'Grass', 'generation' => 'Gen VIII', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Rillaboom', 'image' => 'thwackey.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 802, 'final_evolution_id' => null],
        802 => ['id' => 802, 'pokedex_number' => '#0812', 'name' => 'Rillaboom', 'type' => 'Grass', 'generation' => 'Gen VIII', 'ability' => 'Overgrow', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'rillaboom.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        803 => ['id' => 803, 'pokedex_number' => '#0814', 'name' => 'Raboot', 'type' => 'Fire', 'generation' => 'Gen VIII', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Cinderace', 'image' => 'raboot.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 804, 'final_evolution_id' => null],
        804 => ['id' => 804, 'pokedex_number' => '#0815', 'name' => 'Cinderace', 'type' => 'Fire', 'generation' => 'Gen VIII', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'cinderace.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        805 => ['id' => 805, 'pokedex_number' => '#0817', 'name' => 'Drizzile', 'type' => 'Water', 'generation' => 'Gen VIII', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Inteleon', 'image' => 'drizzile.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 806, 'final_evolution_id' => null],
        806 => ['id' => 806, 'pokedex_number' => '#0818', 'name' => 'Inteleon', 'type' => 'Water', 'generation' => 'Gen VIII', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Final Form', 'image' => 'inteleon.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        807 => ['id' => 807, 'pokedex_number' => '#0820', 'name' => 'Greedent', 'type' => 'Normal', 'generation' => 'Gen VIII', 'ability' => 'Cheek Pouch', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'greedent.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        808 => ['id' => 808, 'pokedex_number' => '#0822', 'name' => 'Corvisquire', 'type' => 'Flying', 'generation' => 'Gen VIII', 'ability' => 'Keen Eye', 'habitat' => 'Grasslands', 'evolution' => 'Corviknight', 'image' => 'corvisquire.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 809, 'final_evolution_id' => null],
        809 => ['id' => 809, 'pokedex_number' => '#0823', 'name' => 'Corviknight', 'type' => 'Flying/Steel', 'generation' => 'Gen VIII', 'ability' => 'Pressure', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'corviknight.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        810 => ['id' => 810, 'pokedex_number' => '#0825', 'name' => 'Dottler', 'type' => 'Bug/Psychic', 'generation' => 'Gen VIII', 'ability' => 'Swarm', 'habitat' => 'Forests', 'evolution' => 'Orbeetle', 'image' => 'dottler.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 811, 'final_evolution_id' => null],
        811 => ['id' => 811, 'pokedex_number' => '#0826', 'name' => 'Orbeetle', 'type' => 'Bug/Psychic', 'generation' => 'Gen VIII', 'ability' => 'Swarm', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'orbeetle.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        812 => ['id' => 812, 'pokedex_number' => '#0828', 'name' => 'Thievul', 'type' => 'Dark', 'generation' => 'Gen VIII', 'ability' => 'Run Away', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'thievul.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        813 => ['id' => 813, 'pokedex_number' => '#0830', 'name' => 'Eldegoss', 'type' => 'Grass', 'generation' => 'Gen VIII', 'ability' => 'Cotton Down', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'eldegoss.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        814 => ['id' => 814, 'pokedex_number' => '#0832', 'name' => 'Dubwool', 'type' => 'Normal', 'generation' => 'Gen VIII', 'ability' => 'Fluffy', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'dubwool.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        815 => ['id' => 815, 'pokedex_number' => '#0834', 'name' => 'Drednaw', 'type' => 'Water/Rock', 'generation' => 'Gen VIII', 'ability' => 'Strong Jaw', 'habitat' => 'Water\'s Edge', 'evolution' => 'Final Form', 'image' => 'drednaw.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],

        // GEN IX SHOWCASE (81-90)
        81 => ['id' => 81, 'pokedex_number' => '#0906', 'name' => 'Sprigatito', 'type' => 'Grass', 'generation' => 'Gen IX', 'ability' => 'Overgrow', 'habitat' => 'Grasslands', 'evolution' => 'Floragato', 'image' => 'sprigatito.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 901, 'final_evolution_id' => 902],
        82 => ['id' => 82, 'pokedex_number' => '#0909', 'name' => 'Fuecoco', 'type' => 'Fire', 'generation' => 'Gen IX', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Crocalor', 'image' => 'fuecoco.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 903, 'final_evolution_id' => 904],
        83 => ['id' => 83, 'pokedex_number' => '#0912', 'name' => 'Quaxly', 'type' => 'Water', 'generation' => 'Gen IX', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Quaxwell', 'image' => 'quaxly.png', 'role' => 'starter', 'is_showcase' => true, 'next_evolution_id' => 905, 'final_evolution_id' => 906],
        84 => ['id' => 84, 'pokedex_number' => '#0915', 'name' => 'Lechonk', 'type' => 'Normal', 'generation' => 'Gen IX', 'ability' => 'Aroma Veil', 'habitat' => 'Grasslands', 'evolution' => 'Oinkologne', 'image' => 'lechonk.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 907, 'final_evolution_id' => null],
        85 => ['id' => 85, 'pokedex_number' => '#0917', 'name' => 'Tarountula', 'type' => 'Bug', 'generation' => 'Gen IX', 'ability' => 'Insomnia', 'habitat' => 'Grasslands', 'evolution' => 'Spidops', 'image' => 'tarountula.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 908, 'final_evolution_id' => null],
        86 => ['id' => 86, 'pokedex_number' => '#0919', 'name' => 'Nymble', 'type' => 'Bug', 'generation' => 'Gen IX', 'ability' => 'Swarm', 'habitat' => 'Grasslands', 'evolution' => 'Lokix', 'image' => 'nymble.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 909, 'final_evolution_id' => null],
        87 => ['id' => 87, 'pokedex_number' => '#0921', 'name' => 'Pawmi', 'type' => 'Electric', 'generation' => 'Gen IX', 'ability' => 'Static', 'habitat' => 'Grasslands', 'evolution' => 'Pawmo', 'image' => 'pawmi.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 910, 'final_evolution_id' => 911],
        88 => ['id' => 88, 'pokedex_number' => '#0924', 'name' => 'Tandemaus', 'type' => 'Normal', 'generation' => 'Gen IX', 'ability' => 'Run Away', 'habitat' => 'Forests', 'evolution' => 'Maushold', 'image' => 'tandemaus.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 912, 'final_evolution_id' => null],
        89 => ['id' => 89, 'pokedex_number' => '#0926', 'name' => 'Fidough', 'type' => 'Fairy', 'generation' => 'Gen IX', 'ability' => 'Own Tempo', 'habitat' => 'Grasslands', 'evolution' => 'Dachsbun', 'image' => 'fidough.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 913, 'final_evolution_id' => null],
        90 => ['id' => 90, 'pokedex_number' => '#0928', 'name' => 'Smoliv', 'type' => 'Grass/Normal', 'generation' => 'Gen IX', 'ability' => 'Early Bird', 'habitat' => 'Grasslands', 'evolution' => 'Dolliv', 'image' => 'smoliv.png', 'role' => 'normal', 'is_showcase' => true, 'next_evolution_id' => 914, 'final_evolution_id' => 915],

        // IX Evolutions (901+)
        901 => ['id' => 901, 'pokedex_number' => '#0907', 'name' => 'Floragato', 'type' => 'Grass', 'generation' => 'Gen IX', 'ability' => 'Overgrow', 'habitat' => 'Grasslands', 'evolution' => 'Meowscarada', 'image' => 'floragato.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 902, 'final_evolution_id' => null],
        902 => ['id' => 902, 'pokedex_number' => '#0908', 'name' => 'Meowscarada', 'type' => 'Grass/Dark', 'generation' => 'Gen IX', 'ability' => 'Overgrow', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'meowscarada.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        903 => ['id' => 903, 'pokedex_number' => '#0910', 'name' => 'Crocalor', 'type' => 'Fire', 'generation' => 'Gen IX', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Skeledirge', 'image' => 'crocalor.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 904, 'final_evolution_id' => null],
        904 => ['id' => 904, 'pokedex_number' => '#0911', 'name' => 'Skeledirge', 'type' => 'Fire/Ghost', 'generation' => 'Gen IX', 'ability' => 'Blaze', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'skeledirge.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        905 => ['id' => 905, 'pokedex_number' => '#0913', 'name' => 'Quaxwell', 'type' => 'Water', 'generation' => 'Gen IX', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Quaquaval', 'image' => 'quaxwell.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 906, 'final_evolution_id' => null],
        906 => ['id' => 906, 'pokedex_number' => '#0914', 'name' => 'Quaquaval', 'type' => 'Water/Fighting', 'generation' => 'Gen IX', 'ability' => 'Torrent', 'habitat' => 'Water\'s Edge', 'evolution' => 'Final Form', 'image' => 'quaquaval.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        907 => ['id' => 907, 'pokedex_number' => '#0916', 'name' => 'Oinkologne', 'type' => 'Normal', 'generation' => 'Gen IX', 'ability' => 'Lingering Aroma', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'oinkologne.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        908 => ['id' => 908, 'pokedex_number' => '#0918', 'name' => 'Spidops', 'type' => 'Bug', 'generation' => 'Gen IX', 'ability' => 'Stakeout', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'spidops.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        909 => ['id' => 909, 'pokedex_number' => '#0920', 'name' => 'Lokix', 'type' => 'Bug/Dark', 'generation' => 'Gen IX', 'ability' => 'Swarm', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'lokix.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        910 => ['id' => 910, 'pokedex_number' => '#0922', 'name' => 'Pawmo', 'type' => 'Electric/Fighting', 'generation' => 'Gen IX', 'ability' => 'Volt Absorb', 'habitat' => 'Grasslands', 'evolution' => 'Pawmot', 'image' => 'pawmo.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 911, 'final_evolution_id' => null],
        911 => ['id' => 911, 'pokedex_number' => '#0923', 'name' => 'Pawmot', 'type' => 'Electric/Fighting', 'generation' => 'Gen IX', 'ability' => 'Volt Absorb', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'pawmot.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        912 => ['id' => 912, 'pokedex_number' => '#0925', 'name' => 'Maushold', 'type' => 'Normal', 'generation' => 'Gen IX', 'ability' => 'Friend Guard', 'habitat' => 'Forests', 'evolution' => 'Final Form', 'image' => 'maushold.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        913 => ['id' => 913, 'pokedex_number' => '#0927', 'name' => 'Dachsbun', 'type' => 'Fairy', 'generation' => 'Gen IX', 'ability' => 'Well-Baked Body', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'dachsbun.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
        914 => ['id' => 914, 'pokedex_number' => '#0929', 'name' => 'Dolliv', 'type' => 'Grass/Normal', 'generation' => 'Gen IX', 'ability' => 'Seed Sower', 'habitat' => 'Grasslands', 'evolution' => 'Arboliva', 'image' => 'dolliv.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => 915, 'final_evolution_id' => null],
        915 => ['id' => 915, 'pokedex_number' => '#0930', 'name' => 'Arboliva', 'type' => 'Grass/Normal', 'generation' => 'Gen IX', 'ability' => 'Seed Sower', 'habitat' => 'Grasslands', 'evolution' => 'Final Form', 'image' => 'arboliva.png', 'role' => 'normal', 'is_showcase' => false, 'next_evolution_id' => null, 'final_evolution_id' => null],
    ];

    public function index(Request $request)
    {
        $selectedGen = $request->query('gen', 'Gen I');
        
        // ONLY GET SHOWCASE POKEMON (Total 10: 3 starters + 7 normals)
        $allPokemon = collect($this->pokemonData)
            ->where('generation', $selectedGen)
            ->where('is_showcase', true);
        
        $starters = $allPokemon->where('role', 'starter')->values();
        $normalList = $allPokemon->where('role', 'normal')->values();
        
        $generations = ['Gen I', 'Gen II', 'Gen III', 'Gen IV', 'Gen V', 'Gen VI', 'Gen VII', 'Gen VIII', 'Gen IX'];

        return view('pokedex.index', compact('starters', 'normalList', 'generations', 'selectedGen'));
    }

    public function show($id)
    {
        if (!isset($this->pokemonData[$id])) {
            abort(404);
        }

        $pokemon = $this->pokemonData[$id];
        
        // Find evolutions (can link to non-showcase pokemon)
        $nextEvolution = null;
        if (isset($pokemon['next_evolution_id']) && isset($this->pokemonData[$pokemon['next_evolution_id']])) {
            $nextEvolution = $this->pokemonData[$pokemon['next_evolution_id']];
        }

        $finalEvolution = null;
        if (isset($pokemon['final_evolution_id']) && isset($this->pokemonData[$pokemon['final_evolution_id']])) {
            $finalEvolution = $this->pokemonData[$pokemon['final_evolution_id']];
        }

        return view('pokedex.show', compact('pokemon', 'nextEvolution', 'finalEvolution'));
    }

    public function management()
    {
        // Sort by ID to keep table stable
        $pokemonList = collect($this->pokemonData)->sortBy('id');
        return view('pokedex.management', compact('pokemonList'));
    }

    public function uploadImage(Request $request, $id)
    {
        $request->validate([
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        if (!isset($this->pokemonData[$id])) {
            return back()->with('error', 'Pokémon not found.');
        }

        $pokemon = $this->pokemonData[$id];
        $imageName = $pokemon['image'];

        $request->image->move(public_path('images/pokedex'), $imageName);

        return back()->with('success', 'Image uploaded successfully for ' . $pokemon['name']);
    }

    public function deleteImage($id)
    {
        if (!isset($this->pokemonData[$id])) {
            return back()->with('error', 'Pokémon not found.');
        }

        $pokemon = $this->pokemonData[$id];
        $imagePath = public_path('images/pokedex/' . $pokemon['image']);

        if (File::exists($imagePath)) {
            File::delete($imagePath);
            return back()->with('success', 'Image deleted successfully for ' . $pokemon['name']);
        }

        return back()->with('error', 'Image file not found on server.');
    }
}
